### ISSUE TITLE
Cannot import NLTK stopwords after install

### ISSUE THREAD

**Issue by ksednew** [heroku/heroku-buildpack-python#685] opened 2018-04-19 19:34 UTC
On a Mac using Python 3.6 and Anaconda. Have installed NLTK and used both command line and manual download of stop words. I see the stop word folder in NLTK folder, but cannot get it to load in my Jupyter notebook:

from nltk.corpus import stopwords 

LookupError                               Traceback (most recent call last)
/anaconda3/lib/python3.6/site-packages/nltk/corpus/util.py in __load(self)
     79             except LookupError as e:
---> 80                 try: root = nltk.data.find('{}/{}'.format(self.subdir, zip_name))
     81                 except LookupError: raise e

/anaconda3/lib/python3.6/site-packages/nltk/data.py in find(resource_name, paths)
    672     resource_not_found = '\n%s\n%s\n%s\n' % (sep, msg, sep)
--> 673     raise LookupError(resource_not_found)
    674 

LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  Searched in:
    - '/Users/ksednew/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/anaconda3/nltk_data'
    - '/anaconda3/lib/nltk_data'
**********************************************************************

During handling of the above exception, another exception occurred:

LookupError                               Traceback (most recent call last)
<ipython-input-35-4ceb335a538b> in <module>()
      1 from nltk.corpus import stopwords
----> 2 stop = stopwords.words("english")
      3 def stopwords(x):
      4     x = re.sub("[^a-z\s]", " ", x.lower())
      5     x = [w for w in x.split() 

/anaconda3/lib/python3.6/site-packages/nltk/corpus/util.py in __getattr__(self, attr)
    114             raise AttributeError("LazyCorpusLoader object has no attribute '__bases__'")
    115 
--> 116         self.__load()
    117         # This looks circular, but its not, since __load() changes our
    118         # __class__ to something new:

/anaconda3/lib/python3.6/site-packages/nltk/corpus/util.py in __load(self)
     79             except LookupError as e:
     80                 try: root = nltk.data.find('{}/{}'.format(self.subdir, zip_name))
---> 81                 except LookupError: raise e
     82 
     83         # Load the corpus.

/anaconda3/lib/python3.6/site-packages/nltk/corpus/util.py in __load(self)
     76         else:
     77             try:
---> 78                 root = nltk.data.find('{}/{}'.format(self.subdir, self.__name))
     79             except LookupError as e:
     80                 try: root = nltk.data.find('{}/{}'.format(self.subdir, zip_name))

/anaconda3/lib/python3.6/site-packages/nltk/data.py in find(resource_name, paths)
    671     sep = '*' * 70
    672     resource_not_found = '\n%s\n%s\n%s\n' % (sep, msg, sep)
--> 673     raise LookupError(resource_not_found)
    674 
    675 

LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  Searched in:
    - '/Users/ksednew/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/anaconda3/nltk_data'
    - '/anaconda3/lib/nltk_data'
**********************************************************************
I have tried placing copies the stopwords folder in various places (where it says it searched) as well as in the corpus folder and still no luck. Any ideas?

**Comment by kennethreitz** [comment] 2018-04-20 10:53
We have official support for corpora, but I believe it does not function properly on Python 3.6. I will have to investigate.

**Comment by ksednew** [comment] 2018-04-20 12:26
Interesting, I thought on my other Mac running the same versions, it had worked, but I may be wrong. 

I will add that I was not able to download the Stopwords corpora because of issues involving my company's proxy:

nltk.download('stopwords')
[nltk_data] Error loading stopwords: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed
[nltk_data]     (_ssl.c:833)>

If you have ideas for that, maybe that would solve it. I'm wondering if I'm just dropping the manually downloaded version in the wrong place.

**Comment by sigmavirus24** [comment] 2018-06-28 17:42
Are there any updates to this? It seems no one every commented as to whether this is a problem with the third-party's support of Python 3.6 or something else.

Further, it sounds like this is a problem on your local machine @ksednew and I'm not certain how this is relevant to the buildpack.

**Comment by ksednew** [comment] 2018-06-28 20:34
I never figured this out. Still looking for support at my company. Will
update if it’s solved.

**Comment by khemanta** [comment] 2018-07-03 09:45
Hemants-MacBook-Pro:TextSummarizer khemant$ python2
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 29 2018, 20:59:26) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import nltk
>>> from nltk.tokenize import sent_tokenize, word_tokenize
>>> from nltk.corpus import stopwords
>>> stop = set(stopwords.words('english'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nltk/corpus/util.py", line 116, in __getattr__
    self.__load()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nltk/corpus/util.py", line 81, in __load
    except LookupError: raise e
LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  Searched in:
    - '/Users/khemant/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/Library/Frameworks/Python.framework/Versions/2.7/nltk_data'
    - '/Library/Frameworks/Python.framework/Versions/2.7/share/nltk_data'
    - '/Library/Frameworks/Python.framework/Versions/2.7/lib/nltk_data'
**********************************************************************

>>> nltk.download('stopwords')
[nltk_data] Error loading stopwords: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed
[nltk_data]     (_ssl.c:726)>
False

This is really surprising.

**Comment by sigmavirus24** [comment] 2018-07-03 13:09
@khemanta this is not running on Heroku. It seems this is an issue with your local installations. I can not help you with this but I suspect folks on [StackOverflow](https://stackoverflow.com) can. Cheers

**Comment by mohitlamba2302** [comment] 2018-10-01 19:34
@ksednew  Try using averaged_perceptron_tagger module from the nltk.download() method.
Also do restart the IDE after unzipping completes. and then run your code base.

**Comment by CaseyFaist** [comment] 2018-10-11 19:11
From comments, this sounds like problems in local instances, which the buildpack can't address. Closing the issue.

**Closed by CaseyFaist** 2018-10-11 19:11 UTC

**Comment by Nikk-27** [comment] 2020-06-16 11:06
@ksednew did you get any help with issue, I'm having the same with my linux os

**Comment by ksednew** [comment] 2020-06-18 19:45
Never figured it out sorry!

**Comment by edmorley** [comment] 2020-07-07 09:14
Is anyone experiencing this when run on Heroku, or only locally?

**Comment by raheebashraf** [comment] 2020-07-28 11:57
I'm experiencing this when running on heruko only. Works fine in my local.

**Comment by edmorley** [comment] 2020-07-28 12:53
@raheebashraf Hi! Please could you open a new issue with steps to reproduce? :-)

**Comment by Jheel-patel** [comment] 2020-09-21 15:45
Experienced same error while working on google colab

**Comment by edmorley** [comment] 2020-10-03 17:10
@Jheel-patel Hi! Could you open a new issue with steps to reproduce?

**Comment by gowrishec** [comment] 2021-04-30 14:19
I am using below code to use stopwords through jupyter hub, I have hosted jupyter hub on AWS DLAMI Linux server.

python3 -m nltk.downloader stopwords
python3 -m nltk.downloader words
python3 -m nltk.downloader punkt
from nltk.corpus import words
from nltk.corpus import stopwords

python3
>>>from nltk.corpus import stopwords
>>>stop_words = set(stopwords.words("english"))
>>>print(stop_words)
This works fine while running in python terminal.

But when I try below in Jupyternotebook its failing with error. Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

$python3
>>> import nltk 
>>> nltk.download('stopwords') [nltk_data] Downloading package stopwords to /root/nltk_data... [nltk_data]   Package stopwords is already up-to-date!

**Comment by emoryr** [comment] 2021-06-17 16:35
Well, I still have the same problem. But one way to work around this was to download it to my local machine and then via Dockerfile copy that to my container.
This solved the problem to Heroku.

Regarding the problem, I suspect that in the pushing process, the content is downloaded and saved in a different path. That's the reason why the container couldn't find the nltk_data. 

I will investigate this and if I found a better solution I will update it.

**Comment by divyasv2000** [comment] 2021-07-17 11:35
> Experienced same error while working on google colab

run the command "nltk.download('stopwords')"in a separate cell just above the cell in which error occured.. i was facing the same issue in the colab but its running now.. after doing this.

**Comment by ayreen2** [comment] 2021-11-05 19:44
> > Experienced same error while working on google colab
> 
> run the command "nltk.download('stopwords')"in a separate cell just above the cell in which error occured.. i was facing the same issue in the colab but its running now.. after doing this.

it is working thank you.

**Comment by Abhi5555555555** [comment] 2023-01-27 13:49
i also facing the same issue if any one know the solution please let me know 
---------------------------------------------------------------------------
LookupError                               Traceback (most recent call last)
File ~\anaconda3\lib\site-packages\nltk\corpus\util.py:84, in LazyCorpusLoader.__load(self)
     83 try:
---> 84     root = nltk.data.find(f"{self.subdir}/{zip_name}")
     85 except LookupError:

File ~\anaconda3\lib\site-packages\nltk\data.py:583, in find(resource_name, paths)
    582 resource_not_found = f"\n{sep}\n{msg}\n{sep}\n"
--> 583 raise LookupError(resource_not_found)

LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords.zip/stopwords/

  Searched in:
    - 'C:\\Users\\Abhishek Pandey/nltk_data'
    - 'C:\\Users\\Abhishek Pandey\\anaconda3\\nltk_data'
    - 'C:\\Users\\Abhishek Pandey\\anaconda3\\share\\nltk_data'
    - 'C:\\Users\\Abhishek Pandey\\anaconda3\\lib\\nltk_data'
    - 'C:\\Users\\Abhishek Pandey\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - 'path_to_nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

LookupError                               Traceback (most recent call last)
Input In [20], in <cell line: 1>()
----> 1 sw = stopwords.words('english')

File ~\anaconda3\lib\site-packages\nltk\corpus\util.py:121, in LazyCorpusLoader.__getattr__(self, attr)
    118 if attr == "__bases__":
    119     raise AttributeError("LazyCorpusLoader object has no attribute '__bases__'")
--> 121 self.__load()
    122 # This looks circular, but its not, since __load() changes our
    123 # __class__ to something new:
    124 return getattr(self, attr)

File ~\anaconda3\lib\site-packages\nltk\corpus\util.py:86, in LazyCorpusLoader.__load(self)
     84             root = nltk.data.find(f"{self.subdir}/{zip_name}")
     85         except LookupError:
---> 86             raise e
     88 # Load the corpus.
     89 corpus = self.__reader_cls(root, *self.__args, **self.__kwargs)

File ~\anaconda3\lib\site-packages\nltk\corpus\util.py:81, in LazyCorpusLoader.__load(self)
     79 else:
     80     try:
---> 81         root = nltk.data.find(f"{self.subdir}/{self.__name}")
     82     except LookupError as e:
     83         try:

File ~\anaconda3\lib\site-packages\nltk\data.py:583, in find(resource_name, paths)
    581 sep = "*" * 70
    582 resource_not_found = f"\n{sep}\n{msg}\n{sep}\n"
--> 583 raise LookupError(resource_not_found)

LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load corpora/stopwords

  Searched in:
    - 'C:\\Users\\Abhishek Pandey/nltk_data'
    - 'C:\\Users\\Abhishek Pandey\\anaconda3\\nltk_data'
    - 'C:\\Users\\Abhishek Pandey\\anaconda3\\share\\nltk_data'
    - 'C:\\Users\\Abhishek Pandey\\anaconda3\\lib\\nltk_data'
    - 'C:\\Users\\Abhishek Pandey\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - 'path_to_nltk_data'
**********************************************************************

**Comment by edmorley** [comment] 2023-01-27 13:55
This buildpack does not use Anaconda, and does not run on Windows - so has nothing to do with the more recent issues posted to this thread.

If you're having issues with NLTK or Anaconda, please first read their docs and failing that, follow any support/issue reporting processes they document instead:
https://www.nltk.org/
https://www.anaconda.com/

If someone has an issue with using NLTK **on Heroku** during a Heroku build (not locally), please open a support ticket (https://help.heroku.com).

I'm locking this issue now, since otherwise people finding this thread via search engines are just going to keep commenting here even though it has nothing to do with their problem.
