### ISSUE TITLE
Collectstatic dry run failures need to be more informative

### ISSUE THREAD

**Issue by stickywes** [heroku/heroku-buildpack-python#237] opened 2015-07-23 17:57 UTC
I recently ran into a problem where, after pushing to Heroku, the collectstatic step would fail.

The behavior in the collectstatic step when the dry run fails is to recommend running the command.
```
        echo "       Collectstatic configuration error. To debug, run:"
        echo "       $ heroku run python $MANAGE_FILE collectstatic --noinput"
```
However, this is not always the way to diagnose the problem.  I was stuck with a website that suddenly broke after a buildpack update because the dry run failed, but 'heroku run python $MANAGE_FILE collectstatic --noinput"' ran perfectly fine.

Something nicer than sending errors to /dev/null should probably be happening.  Even something as dumb as 
```
python $MANAGE_FILE collectstatic --dry-run --noinput &> .collectstatic_errors
```
would have saved me hours of time.

**Comment by dtran320** [comment] 2015-08-07 00:06
@stickywes Currently trying to debug this exact issue. 
```python
heroku run python manage.py collectstatic --noinput
```
Runs fine, but deploying always fails with:
```python
remote:        Collectstatic configuration error. To debug, run:
remote:        $ heroku run python manage.py collectstatic --noinput
```

**Comment by dtran320** [comment] 2015-08-07 00:08
Ah, looks like my issue is due to https://github.com/heroku/heroku-buildpack-python/issues/223

**Comment by kennethreitz** [comment] 2015-08-07 20:32
@stickywes I really like the idea of something like this:

    $ collectstatic --dry-run --noinput &> ~/.heroku/python/collectstatic-log

**Comment by stickywes** [comment] 2015-08-07 21:05
@dtran320 Sorry for the late respond; my issue was related to the Geo Django buildpack and some strangeness happening because of [a change to how it was determining paths] (https://github.com/dulaccc/heroku-buildpack-geodjango/issues/4#issuecomment-116769175).  Glad you figured out your underlying cause!

@kennethreitz I can toss at pull request your way; do you think (off the top of your head) there are other places in the buildpack I might want to make similar additions to, or is the collectstatic step a special case?

**Comment by kennethreitz** [comment] 2016-01-27 00:12
@stickywes that would be great! Just collectstatic, it's special.

**Comment by edmorley** [comment] 2016-01-27 00:19
The root cause of this sounds like a Django bug surely? The dry-run shouldn't ever fail but the non-dry-run succeed. Could you file an issue on their tracker? :-)

**Comment by stickywes** [comment] 2016-01-27 16:24
@edmorley This isn't about trying to fix the issue that was causing problems, but about improving  feedback during a build in order for them to fix the problem easier.  See my last post for the actual root cause of the issue.

**Comment by edmorley** [comment] 2016-01-28 10:35
Sorry 'root cause' was a poor choice of words, I was actually referring to this part of the OP:

>  I was stuck with a website that suddenly broke after a buildpack update because the dry run failed, but 'heroku run python $MANAGE_FILE collectstatic --noinput"' ran perfectly fine.

I read that as saying collectstatic failing was conditional on the presence of `--dry-run`, whereas I'm guessing it was more due to where collectstatic was being invoked (ie during compile vs heroku run).

In addition to the improved logging story in this issue, I think we should cache the result of the collectstatic dry run -- such that if it's ever succeeded in the past, we don't allow the compile to complete if it later goes on to fail, to prevent broken sites from being deployed (a la #252). I'm going to put together a PR for this soon.

**Comment by edmorley** [comment] 2016-02-09 13:05
As of v76 (https://github.com/heroku/heroku-buildpack-python/compare/v75...v76):
* dry-run isn't used, and failures are both output to the log, and cause the build to fail (preventing deploying a broken app)
* collectstatic now outputs a traceback to give more context
* `DEBUG_COLLECTSTATIC` can be defined to dump the environment during the build to the log

As such, I think this is now fixed :-)

**Comment by kennethreitz** [comment] 2016-02-09 16:25
😎

**Closed by kennethreitz** 2016-02-09 16:25 UTC
Labels: Idea

**Comment by stickywes** [comment] 2016-02-09 23:02
Awesome!
