### ISSUE TITLE
Upgrade Pipenv/Pip

### ISSUE THREAD

**Issue by alexandrenicol** [heroku/heroku-buildpack-python#1108] opened 2020-11-05 21:17 UTC
# Description

It would be good to be able to use a newer version of *pip* when using *pipenv* and *Pipfile*.

Alternativaly, maybe if both requirements.txt and Pipfile files are in the repository, the buildpack could ignore the Pipfile? 

At the moment, if a Pipfile is in the repository, it automatically goes back to pip version 9.x, which doesn't necessarily allow the build of some dependencies.  

https://github.com/heroku/heroku-buildpack-python/blob/c9504ffd2ebbfd6a4651948af7c50ddbd7924544/bin/steps/python#L178-L186

**Comment by edmorley** [comment] 2020-11-11 11:48
Hi! This is related to #1093 (though that's about being able to override the default version, whereas this seems to be more about changing the default version itself).

I would love to be able to use the same pip for pipenv users as everyone else. The reason it's pinned is:
https://github.com/heroku/heroku-buildpack-python/pull/833#issuecomment-537758441

...though unfortunately no repro case was provided, so it's hard for me to know whether the issue is now fixed.

> Alternativaly, maybe if both requirements.txt and Pipfile files are in the repository, the buildpack could ignore the Pipfile?

I agree this would be a good idea. In a world where the buildpack supports multiple package managers, I think having `requirements.txt` take precedence is best.

**Comment by tolomea** [comment] 2021-02-08 10:14
Just tried to upgrade cryptography and ran face first into this.

Is there any mechanism at all to force newer versions of Pip and Pipenv?

**Comment by FreneticScribbler** [comment] 2021-02-08 22:18
Just a note, you're going to want to avoid using the env var name PIPENV_VERSION when you do finally upgrade the version: https://github.com/pypa/pipenv/issues/3633#issuecomment-478250721

**Comment by timmygee** [comment] 2021-02-10 19:37
This issue has been solved with this fork https://github.com/alan-eu/heroku-buildpack-python

**Closed** 2021-02-11 17:17 UTC

**Comment by edmorley** [comment] 2021-02-12 11:59
Hi! Sorry for the delay in getting this resolved. I've just shipped #1169 for this, and there's a bit more context in:
https://github.com/heroku/heroku-buildpack-python/issues/987#issuecomment-778151804

> Just a note, you're going to want to rename the env var name PIPENV_VERSION

@FreneticScribbler Good spot, thank you :-) I ended up removing the `export` instead, since the variable is only needed in the buildpack script and not by subprocesses. In general there are lots of unnecessary `exports` in the buildpack at the moment - they are on my list to clean up everywhere :-)

**Comment by jsayles** [comment] 2023-01-25 17:48
Any chance we can upgrade Pip to 2022.12.19?  My builds are failing because my Pipenv.lock checksums don't match if I'm running the latest version locally.

**Comment by edmorley** [comment] 2023-01-26 10:00
@jsayles Hi! I've been glancing at the pipenv releases periodically trying to find a release with as few regressions as possible - however it's been hard to find one that doesn't break as many things as it fixes. Some of the more recent releases seem slightly better, so I was planning on upgrading to one of them in the next couple of weeks :-)

**Comment by edmorley** [comment] 2023-02-08 15:20
Pipenv has been updated in #1407.

**Comment by edmorley** [comment] 2023-02-08 15:22
(Adjusting the issue title to make it clearer that it's an old already-closed issue. For any future Pipenv related requests, please open new GitHub issues 🙂)
