### ISSUE TITLE
GEOS and GDAL issues on heroku-18

### ISSUE THREAD

**Issue by pkrefta** [heroku/heroku-buildpack-python#752] opened 2018-09-18 11:32 UTC
Hey,

Today I've created new Heroku app and it was using ```heroku-18``` My project is using geolibraries and they were detected during installation stage. 

I've set ```BUILD_WITH_GEO_LIBRARIES: 1``` and added 
```
    GDAL_LIBRARY_PATH = os.environ.get('GDAL_LIBRARY_PATH')
    GEOS_LIBRARY_PATH = os.environ.get('GEOS_LIBRARY_PATH')
```

to my settings. But when I try to run ```migrate``` it fails with this traceback.

```
remote: Traceback (most recent call last):
remote:   File "manage.py", line 15, in <module>
remote:     execute_from_command_line(sys.argv)
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
remote:     utility.execute()
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
remote:     django.setup()
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
remote:     apps.populate(settings.INSTALLED_APPS)
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
remote:     app_config.import_models()
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
remote:     self.models_module = import_module(models_module_name)
remote:   File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
remote:     return _bootstrap._gcd_import(name[level:], package, level)
remote:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
remote:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
remote:   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
remote:   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
remote:   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
remote:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
remote:   File "/app/core/models.py", line 3, in <module>
remote:     from django.contrib.gis.db.models import PointField
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/gis/db/models/__init__.py", line 3, in <module>
remote:     import django.contrib.gis.db.models.functions  # NOQA
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/gis/db/models/functions.py", line 4, in <module>
remote:     from django.contrib.gis.db.models.fields import BaseSpatialField, GeometryField
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/gis/db/models/fields.py", line 3, in <module>
remote:     from django.contrib.gis import forms, gdal
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/gis/forms/__init__.py", line 3, in <module>
remote:     from .fields import (  # NOQA
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/gis/forms/fields.py", line 2, in <module>
remote:     from django.contrib.gis.geos import GEOSException, GEOSGeometry
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/gis/geos/__init__.py", line 5, in <module>
remote:     from .collections import (  # NOQA
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/gis/geos/collections.py", line 9, in <module>
remote:     from django.contrib.gis.geos.geometry import GEOSGeometry, LinearGeometryMixin
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/gis/geos/geometry.py", line 8, in <module>
remote:     from django.contrib.gis import gdal
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/gis/gdal/__init__.py", line 28, in <module>
remote:     from django.contrib.gis.gdal.datasource import DataSource
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/gis/gdal/datasource.py", line 39, in <module>
remote:     from django.contrib.gis.gdal.driver import Driver
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>
remote:     from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 9, in <module>
remote:     from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
remote:   File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/gis/gdal/libgdal.py", line 47, in <module>
remote:     lgdal = CDLL(lib_path)
remote:   File "/app/.heroku/python/lib/python3.6/ctypes/__init__.py", line 348, in __init__
remote:     self._handle = _dlopen(self._name, mode)
remote: OSError: /app/.heroku/vendor/lib/libgdal.so: cannot open shared object file: No such file or directory
```

BTW - After I degraded to heroku-16 it works just fine.

**Comment by codingjoe** [comment] 2018-09-20 11:55
Same here!

**Comment by codingjoe** [comment] 2018-09-20 12:00
The problem is simple enough, no one has build the binaries yet and uploaded them:

```bash
$ http HEAD https://lang-python.s3.amazonaws.com/heroku-18/libraries/vendor/gdal.tar.gz
HTTP/1.1 404 Not Found
Content-Type: application/xml
Date: Thu, 20 Sep 2018 11:59:43 GMT
Server: AmazonS3
Transfer-Encoding: chunked
x-amz-id-2: D66hPf9UIzM65dpu4RvIb+51bA72B8YoogMev2jZ9ew8rWDe/1WEZLkRN0FabSFS/oWxr1XY9yE=
x-amz-request-id: 369714D17150467F
```

**Comment by codingjoe** [comment] 2018-09-21 07:17
@CaseyFaist can you run bob the builder for all libraries on heroku-18 and deploy them to your bucket?

**Comment by CaseyFaist** [comment] 2018-10-05 19:35
Hey @codingjoe & @pkrefta - sure thing! This got buried in my notifications, so thank you for your patience. I've got a couple releases slated for beginning of next week but I should be able to get these in prod on the same timeline 👍

**Comment by CaseyFaist** [comment] 2018-10-11 18:31
Hey y'all! Thanks for your patience on this. Binaries are built and available now 👍closing issue.

**Closed by CaseyFaist** 2018-10-11 18:31 UTC
