### ISSUE TITLE
in heroku app is not install package in requirements.txt

### ISSUE THREAD

**Issue by Alababdiy** [heroku/heroku-buildpack-python#672] opened 2018-03-25 15:30 UTC
**when i push my project to my app in heroku  skip requirements.txt and not install Any package** 

Traceback (most recent call last):
2018-03-25T15:21:51.775858+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
2018-03-25T15:21:51.775861+00:00 app[web.1]:     worker.init_process()
2018-03-25T15:21:51.775862+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
2018-03-25T15:21:51.775864+00:00 app[web.1]:     self.load_wsgi()
2018-03-25T15:21:51.775866+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
2018-03-25T15:21:51.775868+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2018-03-25T15:21:51.775870+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2018-03-25T15:21:51.775872+00:00 app[web.1]:     self.callable = self.load()
2018-03-25T15:21:51.775874+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2018-03-25T15:21:51.775876+00:00 app[web.1]:     return self.load_wsgiapp()
2018-03-25T15:21:51.775880+00:00 app[web.1]:     return util.import_app(self.app_uri)
2018-03-25T15:21:51.775878+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2018-03-25T15:21:51.775881+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
2018-03-25T15:21:51.775883+00:00 app[web.1]:     __import__(module)
2018-03-25T15:21:51.775886+00:00 app[web.1]:   File "/app/gettingstarted/wsgi.py", line 15, in <module>
2018-03-25T15:21:51.775888+00:00 app[web.1]:     application = get_wsgi_application()
2018-03-25T15:21:51.775891+00:00 app[web.1]:     django.setup(set_prefix=False)
2018-03-25T15:21:51.775889+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2018-03-25T15:21:51.775892+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
2018-03-25T15:21:51.775894+00:00 app[web.1]:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2018-03-25T15:21:51.775896+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
2018-03-25T15:21:51.775897+00:00 app[web.1]:     self._setup(name)
2018-03-25T15:21:51.775901+00:00 app[web.1]:     self._wrapped = Settings(settings_module)
2018-03-25T15:21:51.775899+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 43, in _setup
2018-03-25T15:21:51.775903+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 106, in __init__
2018-03-25T15:21:51.775905+00:00 app[web.1]:     mod = importlib.import_module(self.SETTINGS_MODULE)
2018-03-25T15:21:51.775906+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
2018-03-25T15:21:51.775908+00:00 app[web.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2018-03-25T15:21:51.775909+00:00 app[web.1]:   File "/app/gettingstarted/settings.py", line 14, in <module>
2018-03-25T15:21:51.775911+00:00 app[web.1]:     import django_heroku
2018-03-25T15:21:51.775920+00:00 app[web.1]: ModuleNotFoundError: No module named 'django_heroku'
2018-03-25T15:21:51.776521+00:00 app[web.1]: [2018-03-25 15:21:51 +0000] [8] [INFO] Worker exiting (pid: 8)
2018-03-25T15:21:51.777060+00:00 app[web.1]: [2018-03-25 15:21:51 +0000] [9] [ERROR] Exception in worker process
2018-03-25T15:21:51.777068+00:00 app[web.1]:     worker.init_process()
2018-03-25T15:21:51.777064+00:00 app[web.1]: Traceback (most recent call last):
2018-03-25T15:21:51.777066+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
2018-03-25T15:21:51.777069+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
2018-03-25T15:21:51.777071+00:00 app[web.1]:     self.load_wsgi()
2018-03-25T15:21:51.777072+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
2018-03-25T15:21:51.777074+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2018-03-25T15:21:51.777076+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2018-03-25T15:21:51.777078+00:00 app[web.1]:     self.callable = self.load()
2018-03-25T15:21:51.777080+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2018-03-25T15:21:51.777081+00:00 app[web.1]:     return self.load_wsgiapp()
2018-03-25T15:21:51.777083+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2018-03-25T15:21:51.777085+00:00 app[web.1]:     return util.import_app(self.app_uri)
2018-03-25T15:21:51.777086+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
2018-03-25T15:21:51.777088+00:00 app[web.1]:     __import__(module)
2018-03-25T15:21:51.777090+00:00 app[web.1]:   File "/app/gettingstarted/wsgi.py", line 15, in <module>
2018-03-25T15:21:51.777093+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2018-03-25T15:21:51.777092+00:00 app[web.1]:     application = get_wsgi_application()
2018-03-25T15:21:51.777095+00:00 app[web.1]:     django.setup(set_prefix=False)
2018-03-25T15:21:51.777096+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
2018-03-25T15:21:51.777098+00:00 app[web.1]:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2018-03-25T15:21:51.777100+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
2018-03-25T15:21:51.777101+00:00 app[web.1]:     self._setup(name)
2018-03-25T15:21:51.777103+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 43, in _setup
2018-03-25T15:21:51.777104+00:00 app[web.1]:     self._wrapped = Settings(settings_module)
2018-03-25T15:21:51.777106+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/conf/__init__.py", line 106, in __init__
2018-03-25T15:21:51.777108+00:00 app[web.1]:     mod = importlib.import_module(self.SETTINGS_MODULE)
2018-03-25T15:21:51.777109+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
2018-03-25T15:21:51.777111+00:00 app[web.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2018-03-25T15:21:51.777113+00:00 app[web.1]:   File "/app/gettingstarted/settings.py", line 14, in <module>
2018-03-25T15:21:51.777114+00:00 app[web.1]:     import django_heroku
2018-03-25T15:21:51.777119+00:00 app[web.1]: **ModuleNotFoundError: No module named 'django_heroku'**

requirements.txt:-
```
django-heroku==0.3.1
feedparser==5.2.1
beautifulsoup4==4.6.0
bs4==0.0.1
Django==2.0.2
gunicorn==19.7.1
idna==2.6
oauthlib==2.0.4
psycopg2==2.7.3.1
python-dotenv==0.7.1
pytz==2018.3
requests==2.18.4
requests-oauthlib==0.8.0
SQLAlchemy==1.1.14
urllib3==1.22
Werkzeug==0.12.2
whitenoise==3.3.1
```

runtime.txt :-
python-3.6.3

Procfile:-
`web: gunicorn gettingstarted.wsgi`

**Comment by sigmavirus24** [comment] 2018-06-28 17:38
Hi there @Alababdiy 

I cannot reproduce this issue. Can you share a bit more information about this? Perhaps if you open a support ticket, I can look a little closer at what you have pushed to Heroku and view the build logs to see if I can help you.

It's also worth noting that if you have a Pipfile or Pipfile.lock then we will skip your requirements.txt file (presuming both are present).

There's been no update to this in months and no one else has complained of this, so I'm going to close this.

Cheers,
Ian

**Closed by sigmavirus24** 2018-06-28 17:38 UTC
