### ISSUE TITLE
Do not rebuild on static file changes

### ISSUE THREAD

**Issue by amartya-dev** [heroku/heroku-buildpack-python#934] opened 2020-03-25 11:53 UTC
Currently, at each push, all of the packages specified in the requirements are reinstalled and then the whole application is redeployed. 

Since gunicorn is used, if the changes are in static files like HTML, CSS or JS, we can just reload the server rather than reinstalling all the packages.

**Comment by CaseyFaist** [comment] 2020-03-26 15:31
Thank you for opening an issue! This looks like a duplicate of #909, which has a fix going out this week. Please track the progress of the fix #925 and let me know after a new release has been tagged if you're still seeing this behavior 👍

**Closed by CaseyFaist** 2020-03-26 15:31 UTC
Labels: duplicate
